name: Laravel CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.4.3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Copy .env example
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Update DB config for CI
        run: |
          php artisan config:clear
          sed -i "s/DB_HOST=.*/DB_HOST=127.0.0.1/" .env
          sed -i "s/DB_DATABASE=.*/DB_DATABASE=laravel/" .env
          sed -i "s/DB_USERNAME=.*/DB_USERNAME=root/" .env
          sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=root/" .env

      - name: Run migrations & seed
        run: php artisan migrate --seed

      - name: Run tests
        run: php artisan test --stop-on-failure
