<?php

namespace App\Filament\Resources\CategoryResource\Pages;

use Illuminate\Database\Eloquent\Model;
use Filament\Notifications\Notification;
use App\Services\Category\CategoryService;
use Filament\Resources\Pages\CreateRecord;
use App\Filament\Resources\CategoryResource;
use App\Traits\Category\HasCategoryTranslations;
use App\Filament\Concerns\SendsFilamentNotifications;

/**
 * CreateCategory Page
 * 
 * Filament page for creating new categories with translations.
 * 
 * This page handles:
 * - Form data processing for category creation
 * - Delegates business logic to CategoryService
 * 
 * Workflow:
 * 1. User fills form with translations (en/ar names/descriptions)
 * 2. mutateFormDataBeforeCreate() extracts translations
 * 3. handleRecordCreation() uses CategoryService to create category and save translations
 * 
 * @package App\Filament\Resources\CategoryResource\Pages
 */
class CreateCategory extends CreateRecord
{
    use HasCategoryTranslations, SendsFilamentNotifications;

    protected static string $resource = CategoryResource::class;

    /**
     * Holds EN/AR translation data across the create lifecycle.
     * 
     * This property stores the extracted translation data between
     * mutateFormDataBeforeCreate() and handleRecordCreation() methods.
     */
    private array $translationData = [];

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    /**
     * Process form data before creating the category
     * 
     * This method extracts translation data from the form and stores it
     * for use in handleRecordCreation(). Slug generation is handled by service.
     * 
     * @param array $data - Raw form data from Filament
     * @return array - Cleaned data for category creation (without translations)
     */
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        // Extract translation data and store for later use in service
        $extracted = $this->extractTranslationData($data);
        $this->translationData = $extracted['translations'];

        // Return main data without translations (slug will be generated by service)
        return $extracted['main'];
    }

    /**
     * Handle record creation using CategoryService
     * 
     * This method uses CategoryService to create the category and handle
     * translations. The service handles slug generation and translation saving.
     * 
     * @param array $data - Cleaned form data (without translations)
     * @return Model
     */
    protected function handleRecordCreation(array $data): Model
    {
        $categoryService = app(CategoryService::class);

        // Create category with translations via service
        // Service handles slug generation and translation saving
        $category = $categoryService->createCategory($data, $this->translationData);

        return $category;
    }

    protected function getSavedNotification(): ?Notification
    {
        return self::buildSuccessNotification(
            __('app.messages.category.created_success'),
            __('app.messages.category.created_success_body', ['name' => $this->record->translations->where('local', app()->getLocale())->first()?->name
                ?? $this->record->translations->first()?->name
                ?? $this->record->slug])
        );
    }
}
